exclude: |
  (?x)^(
    .git/.*|
    .github/.*|
    .clang-tidy|
  )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
  - id: no-commit-to-branch
    args: [--branch, main]


- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
    files: \.(c|cc|cxx|cpp|h|hpp|hxx)$

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

- repo: https://github.com/mxmlnrdr/clang_tidy_hook.git
  rev: v0.2.0
  hooks:
  - id: clang-tidy
    name: clang-tidy
    description: Find warnings/errors in C, C++ code
    language: python
    always_run: true
    verbose: true
    files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
    entry: clang-tidy-hook
    args: ['--extra-arg=-w', '-fix-errors']
